//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by image.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_IMAGETYPE                   129
#define IDS_LENGTH_UNIT_PIXEL           130
#define IDS_LENGTH_UNIT_INCH            131
#define IDD_DIALOG_INITIATE             132
#define IDS_LENGTH_UNIT_MM              132
#define IDD_DIALOG_TEST                 133
#define IDD_DIALOG_SEGOUT               134
#define IDD_DIALOG_IMAGEPROP            135
#define IDD_DIALOG_BANDSEL              139
#define IDD_DIALOG_EDGEMODE             141
#define IDD_DIALOG_SUSAN                141
#define IDD_DIALOG_THIN                 143
#define IDD_DIALOG_CANNY                146
#define IDD_DIALOG_MORPH                148
#define IDD_DIALOG_PREVIEW              150
#define IDD_DIALOG_SELPROP              152
#define IDD_DIALOG_FEATUREEXTR          154
#define IDD_DIALOG_CDTHRESH             155
#define IDB_LENA                        157
#define IDD_DIALOG_SETTHRESH            158
#define IDD_DIALOG_RESULTIMAGE          159
#define IDD_DIALOG_MRFOPTIM             160
#define IDC_EDIT_K                      1009
#define IDC_EDIT_MS                     1010
#define IDC_STATIC_K                    1011
#define IDC_STATIC_MS                   1012
#define IDC_EDIT_SIGMA                  1013
#define IDC_STATIC_SIGMA                1014
#define IDC_EDIT_SHOWRES                1015
#define IDC_EDIT_TIME                   1016
#define IDC_EDIT_COMPS                  1018
#define IDC_STATIC_TIME                 1019
#define IDC_STATIC_BITNUM               1020
#define IDC_EDIT_ALPHA                  1022
#define IDC_STATIC_ALPHA                1023
#define IDC_EDIT_IMGATT                 1035
#define IDC_STATIC_VAR                  1036
#define IDC_STATIC_EDGENUM              1037
#define IDC_EDIT_EDGENUM                1038
#define IDC_EDIT_MINISIZE               1039
#define IDC_STATIC_MINSIZE              1040
#define IDC_STATIC_WC                   1041
#define IDC_EDIT_WC                     1042
#define IDC_EDIT_WP                     1043
#define IDC_STATIC_WP                   1044
#define IDC_EDIT_QS                     1045
#define IDC_STATIC_QS                   1046
#define IDC_EDIT_NN                     1047
#define IDC_EDIT_RS                     1048
#define IDC_STATIC_NN                   1049
#define IDC_STATIC_RZ                   1050
#define IDC_EDIT_CX                     1051
#define IDC_STATIC_CX                   1052
#define IDC_EDIT_CY                     1053
#define IDC_STATIC_CY                   1054
#define IDC_EDIT_FR                     1055
#define IDC_STATIC_FR                   1056
#define IDC_EDIT_BT                     1057
#define IDC_EDIT_3BY3                   1058
#define IDC_STATIC_BT                   1059
#define IDC_STATIC_3BY3                 1060
#define IDC_EDIT_LAMDA                  1061
#define IDC_STATIC_LAMDA                1062
#define IDC_EDIT_LOOP                   1063
#define IDC_STATIC_LN                   1064
#define IDC_EDIT_R                      1065
#define IDC_STATIC_R                    1066
#define IDC_STATIC_G                    1067
#define IDC_EDIT_G                      1068
#define IDC_STATIC_B                    1069
#define IDC_EDIT_B                      1070
#define IDC_EDIT_BAND                   1071
#define IDC_STATIC_BANDS                1072
#define IDC_STATIC_NDVI                 1073
#define IDC_EDIT_NDVI                   1074
#define IDC_STATIC_EB                   1075
#define IDC_EDIT_EB                     1076
#define IDC_EDIT_PHI                    1077
#define IDC_STATIC_PHI                  1078
#define IDC_EDIT_R2L                    1079
#define IDC_STATIC_R2L                  1080
#define IDC_EDIT_RI                     1081
#define IDC_STATIC_RANDI                1082
#define IDC_STATIC_Scale                1083
#define IDC_EDIT_SCALE                  1084
#define IDC_STATIC_EM                   1086
#define IDC_STATIC_HEAD                 1086
#define IDC_EDIT_SPEWEI                 1088
#define IDC_EDIT_PACWEI                 1089
#define IDC_STATIC_SPEWEI               1090
#define IDC_STATIC_COMWEI               1091
#define IDC_STATIC_THIN                 1092
#define IDC_COMBO_THIN                  1093
#define IDC_EDIT_TYPE                   1094
#define IDC_STATIC_TYPE                 1095
#define IDC_STATIC_HEADLINE             1096
#define IDC_EDIT_LOW                    1098
#define IDC_EDIT_HIGH                   1099
#define IDC_STATIC_SIG                  1100
#define IDC_STATIC_LOW                  1101
#define IDC_STATIC_HIGH                 1102
#define IDC_STATIC_SGAP                 1103
#define IDC_STATIC_LOWGAP               1104
#define IDC_STATIC_HIGHGAP              1105
#define IDC_STATIC_MASK                 1106
#define IDC_STATIC_3X3                  1111
#define IDC_STATIC_GAUSS                1112
#define IDC_RADIO_GAUSSIAN              1128
#define IDC_RADIO_3X3                   1129
#define IDC_EDIT_EBAND                  1130
#define IDC_STATIC_EBAND                1131
#define IDC_COMBO_MORPH                 1132
#define IDC_STATIC_MT                   1133
#define IDC_STATIC_OPT                  1136
#define IDC_RADIO_DM                    1142
#define IDC_RADIO_HOMO                  1143
#define IDC_EDIT_LWARRAY                1144
#define IDC_STATIC_LWA                  1145
#define IDC_SLIDER1                     1146
#define IDC_STATIC_COUNT                1153
#define IDC_STATIC_THRESH               1154
#define IDC_STATIC_MAX                  1155
#define IDC_STATIC_MIN                  1156
#define IDC_COMBO_SELPROP               1157
#define IDC_STATIC_SELPROP              1158
#define IDC_EDIT_TOP                    1159
#define IDC_EDIT_BOT                    1160
#define IDC_EDIT_LEFT                   1161
#define IDC_EDIT_RIGHT                  1162
#define IDC_STATIC_TOP                  1163
#define IDC_STATIC_BOTTOM               1164
#define IDC_STATIC_LEFT                 1165
#define IDC_STATIC_RIGHT                1166
#define IDC_EDIT_MINDIFF                1167
#define IDC_EDIT_MAXDIFF                1168
#define IDC_EDIT_LEVEL                  1169
#define IDC_STATIC_MIND                 1170
#define IDC_STATIC_MAXD                 1171
#define IDC_STATIC_LEVEL                1172
#define IDC_EDIT_NDVITH                 1173
#define IDC_EDIT_BANDWT                 1173
#define IDC_STATIC_NDVITH               1174
#define IDC_SLIDER                      1175
#define IDC_STATIC_PICBOX               1176
#define IDC_EDIT_MINAREA                1177
#define IDC_EDIT_MINWID                 1178
#define IDC_EDIT_MAXLWR                 1179
#define IDC_EDIT_MINCMPCT               1180
#define IDC_STATIC_AREA                 1181
#define IDC_STATIC_MEANW                1182
#define IDC_STATIC_BLWR                 1183
#define IDC_STATIC_COMPCT               1184
#define IDC_STATIC_ASYMM                1185
#define IDC_RESULTIMAGE                 1185
#define IDC_STATIC_MAXAREA              1186
#define IDC_EDIT_MAXAREA                1187
#define IDC_STATIC_MRFCD                1187
#define IDC_EDIT_MINASYM                1188
#define IDC_COMBO_MRF                   1188
#define IDC_STATIC_NUMCLS               1189
#define IDC_EDIT_NC                     1190
#define IDC_STATIC_BETA                 1191
#define IDC_EDIT_BETA                   1192
#define IDC_STATIC_T                    1193
#define IDC_STATIC_BWA                  1193
#define IDC_EDIT_T                      1194
#define IDC_EDIT_LEVELUSE               1194
#define IDC_STATIC_T0                   1195
#define IDC_STATIC_LEVELUSE             1195
#define IDC_EDIT_T0                     1196
#define IDC_STATIC_METRIC               1196
#define IDC_STATIC_C                    1197
#define IDC_COMBO_METRIC                1197
#define IDC_EDIT_C                      1198
#define ID_EDIT_TIFF2BW                 32771
#define ID_PROCESS_HISTOEQUAL           32772
#define ID_VIEW_VARIANCE                32773
#define ON_SEG_GRAPH                    32774
#define ID_SEG_GSHC                     32774
#define ID_SEG_EDGE                     32775
#define ID_SEG_INITIATE                 32776
#define ID_VIEW_TEST                    32777
#define ID_SEG_TREE                     32779
#define ID_VIEW_OUTCOME                 32780
#define ID_VIEW_RED                     32781
#define ID_VIEW_GREEN                   32782
#define ID_VIEW_BLUE                    32783
#define ID_PROCESS_GUASS                32784
#define ID_PREPROCESS_GRAPHSEGSUB       32785
#define ID_PREPROCESS_GRAPH2TREE        32786
#define ID_PREPROCESS_TREESEGSUB        32787
#define ID_PREPROCESS_PRETREESEG        32788
#define ID_PREPROCESS_POSTTREESEG       32789
#define ID_PREPROCESS_GRAPH2TREE8       32790
#define ID_PROCESS_PLOTEDGE             32791
#define ONPROCESSTREESEGINITIATE        32792
#define ID_PREPROCESS_TSINI             32792
#define ID_PREPROCESS_PS                32792
#define ID_VIEW_ALPHA                   32793
#define ID_VIEW_REGIONS                 32794
#define ID_VIEW_DIST                    32795
#define ID_SEG_OCCDE                    32796
#define ID_VIEW_ZOOMIN                  32797
#define ID_VIEW_ZOOMOUT                 32798
#define ID_VIEW_ORIGIN                  32799
#define ID_EVAL_QS                      32800
#define ID_VIEW_CS                      32801
#define ID_EVAL_SIEVE                   32802
#define ID_EVAL_OBJFET                  32803
#define ID_EVAL_COLOR                   32804
#define ID_SEG_DELELONG                 32805
#define ON_SEG_EDGEPOINTS               32806
#define ID_SEG_KILLMINION               32807
#define ON_SEG_REGIONGROW               32808
#define ID_SEG_REGIONLABEL              32809
#define ON_SEG_EXTRALIMN                32810
#define ID_SEG_SEGMENT                  32811
#define ID_FAMS                         32812
#define ID_SC                           32813
#define ID_ZG                           32814
#define ID_SEG_REGMEG                   32814
#define ID_SEG_QT                       32815
#define ID_SEG_GS                       32816
#define ID_SEG_QTHC                     32817
#define ON_EDGE_SUSAN                   32819
#define ON_EDGE_SOBEL                   32820
#define ON_EDGE_CANNY                   32821
#define ID_CLASS_REGPROP                32822
#define ID_SEG_EDGEPOINTS               32823
#define ID_CLASS_ROADCLUMP              32825
#define ID_PREP_SR                      32826
#define ID_CLASS_THIN                   32827
#define ID_PREP_THIN                    32827
#define ID_CLASS_ERODE                  32828
#define ID_SEG_SAVE                     32829
#define ID_PREP_SOBEL                   32831
#define ID_PREP_CANNY                   32832
#define ID_PREP_SUSAN                   32833
#define ID_PREP_PAVAD                   32834
#define ID_PREP_MORPH                   32836
#define ID_CLASS_PREVIEW                32837
#define ID_SEG_SAVETOUR                 32838
#define ID_SEG_EXPORTSHP                32839
#define ID_CLASS_MULTIFEATURE           32840
#define ID_CLASS_CM                     32841
#define ID_CLASS_MULTI_FEAT             32842
#define ID_CLASS_SATHUE                 32843
#define ID_PREP_SATHUE                  32843
#define ID_PREP_TEXTIMG                 32844
#define ID_INVERSE                      32845
#define ID_SEG_RANDINDEX                32846
#define ID_CLASS_MANTHRESH              32847
#define ID_CLASS_BUILDING               32848
#define ID_SEG_MEANSHIFTDZJ             32849
#define ID_PREP_GABORTRANS              32850
#define ID_PREP_ENTROPY                 32851
#define ID_SEG_WATERSHEDV               32852
#define ID_SEG_WATERSHEDG               32853
#define ID_SEG_WATERSHEDSEQ             32854
#define ID_SEG_PYRMEANSHIFT             32855
#define ID_SEG_MEANSHIFTEDISON          32856
#define ID_CLASS_MRFCD                  32857
#define ID_CLASS_COLORMRF               32858
#define ID_CLASS_KMEANS                 32859
#define ID_TEXTURE_ROSINCD              32860
#define ID_TEXTURE_CORRBINARY           32861
#define ID_TEXTURE_GRADCORR             32862
#define ID_PREP_OPENING                 32863
#define ID_TEXTURE_HISTOSTATCD          32864
#define ID_CLASS_BUILDINGISODATA        32865
#define ID_INDICATOR_MPOS               59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32866
#define _APS_NEXT_CONTROL_VALUE         1198
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
